"""add_system_settings_table

Revision ID: a89a172add95
Revises: b2654a3a9f3c
Create Date: 2025-06-20 09:19:07.471686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Define the table structure for use in the data migration
system_settings_table = sa.table('system_settings',
    sa.column('key', sa.String),
    sa.column('value', sa.String)
)

# revision identifiers, used by Alembic.
revision: str = 'a89a172add95'
down_revision: Union[str, Sequence[str], None] = 'b2654a3a9f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    # ### end Alembic commands ###

    # ### Add data seeding for the kill switch ###
    op.bulk_insert(system_settings_table,
        [
            {'key': 'intake_system_enabled', 'value': 'true'},
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
